-- CLIENT TABLE
CREATE TABLE IF NOT EXISTS clients (
    id VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
    subdomain VARCHAR(50) NOT NULL UNIQUE,

    -- COMMON QUERIES
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- FEATURE TABLE
CREATE TABLE IF NOT EXISTS features (
    id VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
    feature VARCHAR(100),
    upvotes INT DEFAULT 0,

    -- REFERENCE VARIABLES
    client_id VARCHAR(50) NOT NULL,

    -- COMMON QUERIES
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- FOREIGN KEY REFERENCES
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

-- TAGS 
CREATE TABLE IF NOT EXISTS tags (
    id VARCHAR(20) NOT NULL UNIQUE PRIMARY KEY,
    tag VARCHAR(20) UNIQUE,
    
    -- REFERENCE VARIABLES
    feature_id VARCHAR(50) NOT NULL,

    -- COMMON QUERIES
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- FOREIGN KEY REFERENCES
    FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE
);